<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WalletAPI.BusinessLogic\WalletAPI.BusinessLogic.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\TransactionModels" />
      <Folder Include="Views\Transaction" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="Views\Account\ичич.cshtml" />
    </ItemGroup>

</Project>
