// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WalletAPI.DataAccess;

#nullable disable

namespace WalletAPI.DataAccess.Migrations
{
    [DbContext(typeof(WalletContext))]
    [Migration("20260224204650_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalletAPI.DataAccess.Entities.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BankType")
                        .HasColumnType("integer");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Amount = 10m,
                            BankType = 0,
                            Currency = 0,
                            LastModified = new DateTime(2026, 2, 24, 20, 46, 50, 377, DateTimeKind.Utc).AddTicks(3770),
                            Type = 1
                        },
                        new
                        {
                            Id = "2",
                            Amount = 20m,
                            BankType = 0,
                            Currency = 2,
                            LastModified = new DateTime(2026, 2, 24, 20, 46, 50, 377, DateTimeKind.Utc).AddTicks(3910),
                            Type = 2
                        },
                        new
                        {
                            Id = "3",
                            Amount = 30m,
                            BankType = 0,
                            Currency = 1,
                            LastModified = new DateTime(2026, 2, 24, 20, 46, 50, 377, DateTimeKind.Utc).AddTicks(3910),
                            Type = 3
                        });
                });

            modelBuilder.Entity("WalletAPI.DataAccess.Entities.TransactionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0977f770-8c4f-4879-8415-45df8fc1e59e",
                            AccountId = "1",
                            Amount = 1000m,
                            LastModified = new DateTime(2026, 2, 24, 20, 46, 50, 378, DateTimeKind.Utc).AddTicks(3080),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "81cdd47d-cc12-470c-8cd2-b52610d6ca4c",
                            AccountId = "2",
                            Amount = 100m,
                            LastModified = new DateTime(2026, 2, 24, 20, 46, 50, 378, DateTimeKind.Utc).AddTicks(3370),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "de8282f3-a93b-4b80-85e1-b119d84291c3",
                            AccountId = "3",
                            Amount = 500m,
                            LastModified = new DateTime(2026, 2, 24, 20, 46, 50, 378, DateTimeKind.Utc).AddTicks(3370),
                            TransactionType = 0
                        });
                });

            modelBuilder.Entity("WalletAPI.DataAccess.Entities.TransactionEntity", b =>
                {
                    b.HasOne("WalletAPI.DataAccess.Entities.AccountEntity", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("WalletAPI.DataAccess.Entities.AccountEntity", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
