// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WalletAPI.DataAccess;

#nullable disable

namespace WalletAPI.DataAccess.Migrations
{
    [DbContext(typeof(WalletContext))]
    [Migration("20260224224047_SeedBankType")]
    partial class SeedBankType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalletAPI.DataAccess.Entities.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BankType")
                        .HasColumnType("integer");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Amount = 10m,
                            BankType = 2,
                            Currency = 0,
                            LastModified = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = "2",
                            Amount = 20m,
                            BankType = 1,
                            Currency = 2,
                            LastModified = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = "3",
                            Amount = 30m,
                            BankType = 2,
                            Currency = 1,
                            LastModified = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 3
                        });
                });

            modelBuilder.Entity("WalletAPI.DataAccess.Entities.TransactionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            AccountId = "1",
                            Amount = 1000m,
                            LastModified = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "bbbbbbb2-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                            AccountId = "2",
                            Amount = 100m,
                            LastModified = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "ccccccc3-cccc-cccc-cccc-cccccccccccc",
                            AccountId = "3",
                            Amount = 500m,
                            LastModified = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 0
                        });
                });

            modelBuilder.Entity("WalletAPI.DataAccess.Entities.TransactionEntity", b =>
                {
                    b.HasOne("WalletAPI.DataAccess.Entities.AccountEntity", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("WalletAPI.DataAccess.Entities.AccountEntity", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
